version: '3.8'
services:
  price_engine:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=debug
      - JUPITER_API_URL=https://public.jupiterapi.com
      - IP_ADDRESS=0.0.0.0
      - PORT=8080
    restart: always